from_latest_tag = false
ignore_merge_commits = false
ignore_fixup_commits = true
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
generate_mono_repository_package_tags = true
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = [
    "echo running pytest",
    "poetry run pytest",
    "echo 'bumping from {{latest}} to {{version}}'",
    "poetry version {{version}}",
    "sed -i '/^__version__/ c__version__ = \"{{version}}\"' termalogger/__init__.py"
]
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
template = "./changelog-template"
authors = [
    { username = "Zentheon", signature = "Zentheon" }
]

[bump_profiles]

[packages]
